const $=id=>document.getElementById(id);let device,server,char,pts=[],pos={x:0,y:0,z:0},vel={x:0,y:0,z:0},last=0,running=false,lastStill=0;
const SERVICE_FILTERS=[]; // connect by device name; discover characteristics after pairing
$('connect').onclick=async()=>{try{device=await navigator.bluetooth.requestDevice({filters:[{namePrefix:'WT'}],optionalServices:['0000ffe5-0000-1000-8000-00805f9a34fb']});server=await device.gatt.connect();let services=await server.getPrimaryServices();for(const s of services){let cs=await s.getCharacteristics();let c=cs.find(x=>x.properties.notify);if(c){char=c;break}}if(!char)throw Error('No notification characteristic found');await char.startNotifications();char.addEventListener('characteristicvaluechanged',packet);$('status').textContent='Connected';$('status').classList.add('on');}catch(e){alert('Bluetooth connection failed: '+e.message)}};
function packet(e){const d=new Uint8Array(e.target.value.buffer);for(let i=0;i<=d.length-11;i++)if(d[i]===0x55&&d[i+1]===0x51){const dv=new DataView(d.buffer,d.byteOffset+i,11);const g=9.80665;let ax=dv.getInt16(2,true)/32768*16*g,ay=dv.getInt16(4,true)/32768*16*g,az=dv.getInt16(6,true)/32768*16*g;integrate(ax,ay,az)}}
function integrate(ax,ay,az){if(!running)return;let now=performance.now();if(!last){last=now;return}let dt=Math.min((now-last)/1000,.05);last=now;let mag=Math.hypot(ax,ay,az),still=Math.abs(mag-9.80665)<.12;if(still){if(!lastStill)lastStill=now;if(now-lastStill>180){vel.x=vel.y=vel.z=0}return}else lastStill=0;
// Raw prototype: gravity/orientation compensation will be calibrated from full IMU packets.
vel.x+=ax*dt;vel.y+=ay*dt;vel.z+=(az-9.80665)*dt;pos.x+=vel.x*dt;pos.y+=vel.y*dt;pos.z+=vel.z*dt;render()}
$('start').onclick=()=>{pos={x:0,y:0,z:0};vel={x:0,y:0,z:0};pts=[{...pos}];last=0;running=true;$('point').disabled=$('close').disabled=false;render()};
$('point').onclick=()=>{pts.push({...pos});render()};$('close').onclick=()=>{if(pts.length>2)pts.push({...pts[0]});render()};$('reset').onclick=()=>{running=false;pts=[];pos={x:0,y:0,z:0};vel={x:0,y:0,z:0};render()};
function render(){let path=[...pts,...(running?[pos]:[])],dist=0;for(let i=1;i<path.length;i++)dist+=Math.hypot(path[i].x-path[i-1].x,path[i].y-path[i-1].y,path[i].z-path[i-1].z);let horiz=Math.hypot(pos.x,pos.y),ft=3.28084;$('distance').textContent=(dist*ft).toFixed(2)+' ft';$('elevation').textContent=(pos.z*ft).toFixed(2)+' ft';$('slope').textContent=(horiz?pos.z/horiz*100:0).toFixed(1)+'%';let area=0;if(pts.length>2)for(let i=0,j=pts.length-1;i<pts.length;j=i++)area+=(pts[j].x*pts[i].y-pts[i].x*pts[j].y);area=Math.abs(area/2)*10.7639;$('area').textContent=area.toFixed(0)+' ft²';$('points').innerHTML=pts.map((p,i)=>'<div class="point"><span>P'+(i+1)+'</span><span>'+((p.x)*ft).toFixed(1)+', '+((p.y)*ft).toFixed(1)+', '+((p.z)*ft).toFixed(1)+' ft</span></div>').join('');draw(path)}
function draw(path){let c=$('map'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;let x=c.getContext('2d');x.scale(d,d);x.fillStyle='#fff';x.fillRect(0,0,r.width,r.height);x.strokeStyle='#e5e7eb';for(let i=0;i<r.width;i+=40){x.beginPath();x.moveTo(i,0);x.lineTo(i,r.height);x.stroke()}for(let i=0;i<r.height;i+=40){x.beginPath();x.moveTo(0,i);x.lineTo(r.width,i);x.stroke()}if(!path.length)return;let xs=path.map(p=>p.x),ys=path.map(p=>p.y),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),scale=Math.min((r.width-50)/(maxx-minx||1),(r.height-50)/(maxy-miny||1));x.strokeStyle='#111827';x.lineWidth=3;x.beginPath();path.forEach((p,i)=>{let px=25+(p.x-minx)*scale,py=r.height-25-(p.y-miny)*scale;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}render();